include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
##  - template: Security/Dependency-Scanning.gitlab-ci.yml => à payer
  - template: Code-Quality.gitlab-ci.yml

stages:
  - test
#
job-analyse:
  stage: test
  script:
    - echo "Running tests Analyse"

